version: '3.8'

services:
  mcp-server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: vulnerable-mcp-server
    ports:
      - "8000:8000"
    networks:
      - research-net
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  research-net:
    driver: bridge
